// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type pages = Collections['pages']['schema']['_output']
export declare const pages: pages[]

export type projects = Collections['projects']['schema']['_output']
export declare const projects: projects[]
