import { motion } from 'motion/react'
import { useId } from 'react'
import { SEGMENTS, VIEW_BOX } from './signatureSegments'

const DEFAULT_SEGMENT_GAP = 0
const DEFAULT_FADE_FRACTION = 0
const EASE = [.28,.1,.62,.98] as const

/**
 * Segments are generated by `scripts/extractSignatureSegments.mjs` from
 * `public/signature.svg` and imported via `./signatureSegments`.
 */

type SignatureProps = {
    className?: string
    drawDelay?: number
    segmentDurations?: number[]
    segmentGap?: number
    fadeFraction?: number
    title?: string
}

export function Signature({
    className,
    drawDelay = 0,
    segmentDurations = [1.5, 0.075],
    segmentGap = DEFAULT_SEGMENT_GAP,
    fadeFraction = DEFAULT_FADE_FRACTION,
    title = 'Signature logo',
}: SignatureProps) {
    const titleId = useId()

    const durations = SEGMENTS.map((_, index) => segmentDurations?.[index])

    let accumulatedDelay = drawDelay

    return (
        <motion.svg
            className={className}
            viewBox={VIEW_BOX}
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            role="img"
            aria-labelledby={titleId}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: drawDelay, duration: 0.3 }}
        >
            <title id={titleId}>{title}</title>

            {SEGMENTS.map((d, index) => {
                const currentDuration = durations[index]
                const pathDelay = accumulatedDelay
                accumulatedDelay += currentDuration + segmentGap

                const fadeDuration = Math.max(0.05, currentDuration * fadeFraction)

                return (
                    <motion.path
                        key={index}
                        d={d}
                        fill="none"
                        stroke="#E5E5E5"
                        strokeWidth={36}
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        initial={{ pathLength: 0, opacity: 0 }}
                        animate={{ pathLength: 1, opacity: 1 }}
                        transition={{
                            pathLength: {
                                delay: pathDelay,
                                duration: currentDuration,
                                ease: EASE,
                            },
                            opacity: {
                                delay: pathDelay,
                                duration: fadeDuration,
                                ease: EASE,
                            },
                        }}
                    />
                )
            })}
        </motion.svg>
    )
}

