import { animate, motion, useMotionValue, useTransform } from 'motion/react'
import { useEffect, useId, useMemo, useRef } from 'react'
import { SEGMENTS, VIEW_BOX } from './signatureSegments'

const DEFAULT_SEGMENT_DURATION = 0.9
const DEFAULT_SEGMENT_GAP = 0
const DEFAULT_SEGMENT_DURATIONS = [2, 0.1]
const MOTION_EASE = [0.42, 0, 0.58, 1] as const
const STROKE_WIDTH = 48

const GLOW_COLOR = 'rgba(150, 150, 255, 1)'
const GLOW_SHADOW = 'drop-shadow(0 0 22px rgba(253, 224, 71, 0.75))'

const PULSE_COLOR = 'rgba(150, 150, 255, 1)'
const DEFAULT_PULSE_FADE_PORTION = 0.3
const PULSE_DURATION = 4
const PULSE_DELAY_AFTER_DRAW = 0.25
const PULSE_LENGTH_RATIO = 0.04
const DEFAULT_PULSE_STROKE_SCALE = 2

/**
 * Segments are generated by `scripts/extractSignatureSegments.mjs` from
 * `public/signature.svg` and imported via `./signatureSegments`.
 */

type SignatureProps = {
  className?: string
  drawDelay?: number
  enableDraw?: boolean
  segmentDuration?: number
  segmentDurations?: number[]
  segmentGap?: number
  title?: string
  pulseStrokeScale?: number
  pulseFadePortion?: number
}

type SegmentConfig = {
  d: string
  delay: number
  duration: number
  pulseStrokeWidth: number
  showPulse: boolean
  pulseFadePortion: number
  enableDraw: boolean
}

function AnimatedSegment({
  d,
  delay,
  duration,
  pulseStrokeWidth,
  showPulse,
  pulseFadePortion,
  enableDraw,
}: SegmentConfig) {
  const pathRef = useRef<SVGPathElement | null>(null)
  const pathLengthValue = useMotionValue(0)
  const pathOpacityValue = useMotionValue(0)
  const glowOpacityValue = useMotionValue(0)
  const glowXValue = useMotionValue(0)
  const glowYValue = useMotionValue(0)
  const totalLengthValue = useMotionValue(0)
  const pulseOffsetProgressValue = useMotionValue(0)
  const pulseOpacityValue = useMotionValue(0)
  const pulseDasharrayValue = useMotionValue('0 1')
  const pulseDashoffsetValue = useTransform(pulseOffsetProgressValue, (progress) => {
    const total = totalLengthValue.get()
    return total * (1 - progress)
  })

  useEffect(() => {
    const pathElement = pathRef.current
    if (!pathElement) return

    const totalLength = pathElement.getTotalLength()
    const startPoint = pathElement.getPointAtLength(0)
    glowXValue.set(startPoint.x)
    glowYValue.set(startPoint.y)
    totalLengthValue.set(totalLength)

    let pulseAnimationControl: ReturnType<typeof animate> | null = null
    let pulseOpacityControl: ReturnType<typeof animate> | null = null
    let pulseStartTimeout: ReturnType<typeof setTimeout> | null = null

    const configurePulse = () => {
      if (showPulse) {
        const pulseLength = Math.max(totalLength * PULSE_LENGTH_RATIO, STROKE_WIDTH * 1.5)
        const pulseGap = Math.max(totalLength - pulseLength, 1)
        pulseDasharrayValue.set(`${pulseLength} ${pulseGap}`)
      } else {
        pulseOpacityValue.set(0)
        pulseDasharrayValue.set('0 1')
      }
    }

    const startPulse = () => {
      if (!showPulse) return
      pulseOffsetProgressValue.set(0)
      const clampedFadePortion = Math.min(Math.max(pulseFadePortion, 0.05), 0.95)
      pulseOpacityControl = animate(pulseOpacityValue, [0, 1, 0], {
        duration: PULSE_DURATION,
        ease: 'linear',
        times: [0, clampedFadePortion, 1],
        repeat: Infinity,
        repeatDelay: 0,
        repeatType: 'loop',
      })
      pulseAnimationControl = animate(pulseOffsetProgressValue, [0, 1], {
        duration: PULSE_DURATION,
        ease: 'linear',
        repeat: Infinity,
        repeatDelay: 0,
        repeatType: 'loop',
      })
    }

    configurePulse()

    if (!enableDraw) {
      pathOpacityValue.set(1)
      pathLengthValue.set(1)
      glowOpacityValue.set(0)
      startPulse()

      return () => {
        if (pulseStartTimeout) {
          clearTimeout(pulseStartTimeout)
        }
        pulseAnimationControl?.stop()
        pulseOpacityControl?.stop()
      }
    }

    const pathOpacityControl = animate(pathOpacityValue, 1, {
      delay,
      duration: 0,
    })

    const glowInDuration = Math.min(0.25, duration)
    const glowOutDuration = Math.min(0.25, duration)

    const glowInControl = animate(glowOpacityValue, 1, {
      delay,
      duration: glowInDuration,
      ease: 'easeOut',
    })

    const progressAnimation = animate(pathLengthValue, 1, {
      delay,
      duration,
      ease: MOTION_EASE,
      onUpdate: (value) => {
        const point = pathElement.getPointAtLength(value * totalLength)
        glowXValue.set(point.x)
        glowYValue.set(point.y)
      },
    })

    progressAnimation.finished.then(() => {
      animate(glowOpacityValue, 0, {
        duration: glowOutDuration,
        ease: 'easeIn',
        onComplete: () => {
          pathOpacityValue.set(1)
          glowOpacityValue.set(0)
          if (showPulse) {
            pulseStartTimeout = setTimeout(() => {
              startPulse()
            }, PULSE_DELAY_AFTER_DRAW * 1000)
          }
        },
      })
    })

    return () => {
      progressAnimation.stop()
      pathOpacityControl.stop()
      glowInControl.stop()
      if (pulseStartTimeout) {
        clearTimeout(pulseStartTimeout)
      }
      pulseAnimationControl?.stop()
      pulseOpacityControl?.stop()
    }
  }, [
    d,
    delay,
    duration,
    enableDraw,
    glowOpacityValue,
    glowXValue,
    glowYValue,
    pathLengthValue,
    pathOpacityValue,
    pulseDasharrayValue,
    pulseOffsetProgressValue,
    pulseOpacityValue,
    pulseFadePortion,
    showPulse,
    totalLengthValue,
  ])

  return (
    <>
      <motion.path
        ref={pathRef}
        d={d}
        fill="none"
        stroke="#E5E5E5"
        strokeWidth={STROKE_WIDTH}
        strokeLinecap="round"
        strokeLinejoin="round"
        style={{ pathLength: pathLengthValue, opacity: pathOpacityValue }}
      />
      <motion.circle
        r={STROKE_WIDTH * 2}
        fill={GLOW_COLOR}
        style={{
          translateX: glowXValue,
          translateY: glowYValue,
          opacity: glowOpacityValue,
          filter: GLOW_SHADOW,
        }}
      />
      {showPulse ? (
        <motion.path
          d={d}
          fill="none"
          stroke={PULSE_COLOR}
          strokeWidth={pulseStrokeWidth}
          strokeLinecap="round"
          strokeLinejoin="round"
          style={{
            pathLength: 1,
            strokeDasharray: pulseDasharrayValue,
            strokeDashoffset: pulseDashoffsetValue,
            opacity: pulseOpacityValue,
          }}
        />
      ) : null}
    </>
  )
}

export function Signature({
  className,
  drawDelay = 0,
  enableDraw = true,
  segmentDuration = DEFAULT_SEGMENT_DURATION,
  segmentDurations = DEFAULT_SEGMENT_DURATIONS,
  segmentGap = DEFAULT_SEGMENT_GAP,
  title = 'Signature logo',
  pulseStrokeScale = DEFAULT_PULSE_STROKE_SCALE,
  pulseFadePortion = DEFAULT_PULSE_FADE_PORTION,
}: SignatureProps) {
  const titleId = useId()

  const segments = useMemo<SegmentConfig[]>(() => {
    let currentDelay = drawDelay
    const pulseStrokeWidth = STROKE_WIDTH * pulseStrokeScale
    return SEGMENTS.map((d, index) => {
      const duration = segmentDurations[index] ?? segmentDuration
      const config: SegmentConfig = {
        d,
        delay: currentDelay,
        duration,
        pulseStrokeWidth,
        showPulse: index === 0,
        pulseFadePortion,
        enableDraw,
      }
      currentDelay += duration + segmentGap
      return config
    })
  }, [
    drawDelay,
    enableDraw,
    segmentDuration,
    segmentDurations,
    segmentGap,
    pulseStrokeScale,
    pulseFadePortion,
  ])

  return (
    <motion.svg
      className={className}
      viewBox={VIEW_BOX}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-labelledby={titleId}
      initial={{ opacity: enableDraw ? 0 : 1 }}
      animate={{ opacity: 1 }}
      transition={{ delay: enableDraw ? drawDelay : 0, duration: 0.3 }}
      style={{ overflow: 'visible' }}
    >
      <title id={titleId}>{title}</title>

      {segments.map(({ d, delay, duration, pulseStrokeWidth, showPulse, pulseFadePortion }) => (
        <AnimatedSegment
          key={`${d}-${delay}-${duration}`}
          d={d}
          delay={delay}
          duration={duration}
          pulseStrokeWidth={pulseStrokeWidth}
          showPulse={showPulse}
          pulseFadePortion={pulseFadePortion}
          enableDraw={enableDraw}
        />
      ))}
    </motion.svg>
  )
}
