import { motion } from 'motion/react'
import { useId } from 'react'
import { SEGMENTS } from './signatureSegments'

const DEFAULT_SEGMENT_DURATION = 0.4
const DEFAULT_SEGMENT_GAP = 0.12

/**
 * Segments are generated by `scripts/extractSignatureSegments.mjs` from
 * `public/signature.svg` and imported via `./signatureSegments`.
 */

type SignatureProps = {
    className?: string
    drawDelay?: number
    segmentDuration?: number
    segmentGap?: number
    title?: string
}

export function Signature({
    className,
    drawDelay = 0,
    segmentDuration = DEFAULT_SEGMENT_DURATION,
    segmentGap = DEFAULT_SEGMENT_GAP,
    title = 'Signature logo',
}: SignatureProps) {
    const titleId = useId()

    return (
        <motion.svg
            className={className}
            viewBox="0 0 972 496"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            role="img"
            aria-labelledby={titleId}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: drawDelay, duration: 0.3 }}
        >
            <title id={titleId}>{title}</title>

            {SEGMENTS.map((d, index) => (
                <motion.path
                    key={index}
                    d={d}
                    fill="none"
                    stroke="#E5E5E5"
                    strokeWidth={12}
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    initial={{ pathLength: 0 }}
                    animate={{ pathLength: 1 }}
                    transition={{
                        delay: drawDelay + index * segmentGap,
                        duration: segmentDuration,
                        ease: 'easeInOut',
                    }}
                />
            ))}
        </motion.svg>
    )
}

